### PR TITLE
Use bundle.run CDN

### PR DESCRIPTION
**Pull request by xtuc**
Since https://github.com/Rich-Harris/packd/issues/10

### CODE REVIEW

**Comment by Rich-Harris** [comment]
A big 👍  on this, as long as we can update bundle.run to new versions of packd relatively easily — how do you see that working? There are a few worthwhile improvements in the last few versions, particularly delegating the bundling/minification to a separate process to stop the server from hanging.

**Comment by xtuc** [comment]
Yes, I still have a few issues with upgrading to the lastest version (https://github.com/Rich-Harris/packd/commit/72d959eeda58ef1a531e327568fe9157f7b4d8d2#commitcomment-23286871). I don't know why these dependencies are so hard to install.

In the future I imagine an automatic deployment process in the CI. I'm currently working on it.

**Comment by xtuc** [comment]
Just FYI i'm going to work on this during the next week. Sorry for the delay.

**Comment by Rich-Harris** [comment]
No worries! packd.now.sh is doing the job for now, albeit with slower response times/higher latency

**Comment by xtuc** [comment]
Alright, PR is here https://github.com/Rich-Harris/packd/pull/28

**Comment by Rich-Harris** [comment]
🎉  thanks @xtuc!

**Pull request merged**
