### PR TITLE
Some tweaks

### PR DESCRIPTION
**Pull request by Conduitry**
- don't have a filename of `:id.html`. This prevents the repo from being cloned on Windows. I'm fine with the site only running under Unix as I can just use WSL, but in order to use text editors running in Windows, the repo needs to be cloned to the main Windows filesystem
- update the readme to remove the `yarn run prep` step, which is no longer necessary, and which in fact errors because that task no longer exists
- update some rollup configs for recently renamed options

### CODE REVIEW

**Comment by Conduitry** [comment]
Actually, we don't want the embedded svelte-app's rollup config updated unless we're using rollup 0.48+, and the embedded package.json still has ^0.47.6. Any reason not to bump that up to the latest version? And I guess the svelte-app.zip would have to be regenerated too.

**Comment by Rich-Harris** [comment]
The svelte-app template is actually pulled from https://github.com/sveltejs/template, so we'll need to update it there. Yep, there's no reason not to use the latest version

**Comment by Conduitry** [comment]
Should the whole `svelte-app` directory just be removed from this repo then?

**Comment by Rich-Harris** [comment]
it probably should, yeah — though there may or may not be problems resulting from `now` disregarding anything in `.gitignore`. Honestly can't remember how that works...

**Comment by Conduitry** [comment]
Bluh I give up. `now` is finicky about which files it deploys (why is `guide.json` deployed even though it's `.gitignore`d?), and there are a lot of files that are checked into the repo that are generated from other files checked into the repo.

**Comment by Rich-Harris** [comment]
Looking at the `now` docs, there's a `now.files` option which can override `.gitignore`. Think we can just use that. Trying it now...

**Pull request merged**
