### PR TITLE
Add ability to view compiled ssr code with repl

### PR DESCRIPTION
**Pull request by DylanPiercey**
This adds the ability to toggle between 'ssr' and 'dom' in the REPL.
There is likely some work to be done here in terms of animations, naming, and bike shedding.

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Cleaned up the PR a bit. Let me know if you have any feedback.

**Comment by Rich-Harris** [comment]
Thanks, this makes sense. In the longer term I think it'd make sense to expose more options (`shared`, `cascade`, `name`, `dev` etc) which would probably involve a somewhat different interface, but no sense in delaying this improvement until then.

If we end up doing that we should probably compile the output specifically for that view, so that it's cleanly separated from the actual bundling. Would be nice to do it all in a web worker as well, so that we can handle more complex examples without clogging up the main thread. All future work though

**Comment by Rich-Harris** [comment]
Unfortunately I had to revert this because of https://github.com/sveltejs/svelte/issues/633 — I'm not able to dig into it right now, will have to investigate later

**Comment by DylanPiercey** [comment]
@Rich-Harris I looked into this a bit and found an issue. Looks like I didn't account for the compile changes [here](https://github.com/sveltejs/svelte.technology/blob/master/shared/routes/Repl/index.html#L713). However it looks like the issue may be a bit deeper since it didn't resolve the issue.

I'll keep looking though.

**Pull request merged**
