### PR TITLE
Improve mobile navigation

### PR DESCRIPTION
**Pull request by flagello**
https://github.com/sveltejs/svelte.technology/pull/36#issuecomment-284824676

<br><br>

<p align="center">
</p>

<p align="center">
</p>

<p align="center">
</p>

<br><br>

Closes #36 (but it's missing the Vue-like current-position).

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks, looking good! A few notes:

* I liked the slide-out menu in https://github.com/sveltejs/svelte.technology/pull/36#issue-210288430 over the fullscreen takeover — it's a more common pattern, and it's less far for someone's thumb to move to make a selection than if it's in the middle of the screen
* We probably only want to use a menu when the screen is small enough to warrant it (say, 400px) — on screens that can accommodate the nav in the header, it makes sense to keep them there because a) the different sections are more discoverable, and b) it's one less interaction
* Let's make the text centre-aligned 😀 

Also, small bug — the REPL no longer fills the screen on desktop (the `main` element should be `calc(100% - 4em)` up to a certain width, then `calc(100% - 7em)` — I think that code got removed 😆).

**Comment by flagello** [comment]
Thanks Rich!

1. What about a bottom aligned version with a container high just enough to contain the items? Although the guide would still need to be fullscreen. If you continue to prefer the slide-out menu, I'll go with it. :)
2. Agreed!
3. Did you mean left-aligned or am I missing something? 😅
4. I can't seem to be able to build with the REPL task in the gobblefile, so can't test exactly — the `7em` measure if I remember correctly is due to the header and footer being respectively `4em` and and `3em` high, correct? I'll fix it in any case — IIRC I adjusted it because I included the footer in the `<main>` element to reflect some other changes.

**Comment by Rich-Harris** [comment]
I think it's fine to have the menu button in the top left, since it's something that only needs to be interacted with infrequently — not something that needs to be in thumb range. And the menu items should probably be near the menu button, so the slide-out menu seems like the best idea to me.

> Although the guide would still need to be fullscreen

Yeah, I think it can be fullscreen at all times, at least vertically. Maybe just a couple of ems shy of full width, so that the user is still aware of where they are and has an easy way to dismiss the sidebar? I actually think you were spot on with this initial mockup:



> Did you mean left-aligned or am I missing something? 😅

Argh, I'm an idiot. Yes, left-aligned!

Exactly, yeah — 4em plus 3em, so that the REPL fills the screen minus the header and footer. (Probably needs to do something different on mobile but that's for another time...)

Cheers 🍺

**Comment by flagello** [comment]
So here is it, mostly.

I'll start by saying that I didn't manage to figure out a way to cleanly detach the header and sidebar from global (for the guide needs) as you requested. Therefore the breakpoint is still at `767px`.

<p align="center">
screen shot 2017-03-12 at 02 54 25
screen shot 2017-03-12 at 02 53 46
</p>

The sidebar now responds to three events:
1. If it's open, `hashchange` closes it (elegant way to close on both link click and scroll change, with the other addition (below))
2. Click outside closes it
3. Menu click

[Screencap](https://cl.ly/021R2v0q0g1h/svelte-mob-nav.mov)

<br>

I've also added section highlighting on scroll along with `location.hash` mutations.

screen shot 2017-03-12 at 03 59 46

[Screencap](https://cl.ly/3w3P2E0D2l1A/svelte-site-sect.mov)

**Comment by flagello** [comment]
I had to remove the `bold` style from the `.active-section` because [Safari goes nuts and makes the links disappear](https://cl.ly/1J0o2M3g2G16/Screen%20Recording%202017-03-12%20at%2004.19%20AM.mov).

**Comment by Rich-Harris** [comment]
Thanks so much!

> Safari goes nuts

why am I not surprised...

**Pull request merged**
